services:
  discovery-server:
    build:
      context: .
      dockerfile: discovery-server/Dockerfile.dev
    container_name: discovery-server
    restart: unless-stopped
    ports:
      - "8761:8761"
      - "5004:5005"
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    networks:
      - todo-net
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8761/actuator/health",
        ]
      interval: 10s
      retries: 5
      start_period: 30s

  postgres-auth:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB_NAME}
      POSTGRES_USER: ${AUTH_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
    ports:
      - "${AUTH_POSTGRES_PORT}:5432"
    networks:
      - todo-net
    volumes:
      - auth_data:/var/lib/postgresql/data

  postgres-todo:
    image: postgres:15-alpine
    container_name: postgres-todo
    environment:
      POSTGRES_DB: ${TODO_POSTGRES_DB_NAME}
      POSTGRES_USER: ${TODO_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${TODO_POSTGRES_PASSWORD}
    ports:
      - "${TODO_POSTGRES_PORT}:5432"
    networks:
      - todo-net
    volumes:
      - todo_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile.dev
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "5005:5005"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SERVER_PORT: 8081
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/${AUTH_POSTGRES_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${AUTH_POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    depends_on:
      discovery-server:
        condition: service_healthy
      postgres-auth:
        condition: service_started
    networks:
      - todo-net

  todo-service:
    build:
      context: .
      dockerfile: todo-service/Dockerfile.dev
    container_name: todo-service
    restart: unless-stopped
    ports:
      - "8082:8082"
      - "5006:5005"
    environment:
      SERVER_PORT: 8082
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-todo:5432/${TODO_POSTGRES_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${TODO_POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${TODO_POSTGRES_PASSWORD}
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    depends_on:
      discovery-server:
        condition: service_healthy
      postgres-todo:
        condition: service_started
    networks:
      - todo-net

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile.dev
    container_name: gateway-service
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "5007:5005"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge

volumes:
  auth_data:
  todo_data:
